# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 22:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logReg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Friend1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend1', to='logReg.User')),
                ('Friend2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend2', to='logReg.User')),
            ],
        ),
    ]
