# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lrApp', '0001_initial'),
        ('quoteApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='author',
            field=models.CharField(default='Dan', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotes',
            name='user',
            field=models.ForeignKey(default='DANO', on_delete=django.db.models.deletion.CASCADE, related_name='sub_user', to='lrApp.User'),
            preserve_default=False,
        ),
    ]
