# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteApp', '0003_auto_20170330_0034'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotesManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
