# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('alias', models.CharField(max_length=35)),
                ('email', models.EmailField(max_length=55)),
                ('password', models.CharField(max_length=100)),
                ('DOB', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
